apiVersion: knappek.com/v1alpha1
kind: MongoDBAtlasProject
metadata:
  name: example-project
spec:
  # Add fields here
  publicKey: "toppaljd"
  orgID: "5c4a2a55553855344780cf5f"
  privateKey:
    valueFrom:
      secretKeyRef:
        name: "example-monogdb-atlas-project"
        key: "privateKey"
