apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbatlas-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodbatlas-operator
  template:
    metadata:
      labels:
        name: mongodbatlas-operator
    spec:
      serviceAccountName: mongodbatlas-operator
      containers:
        - name: mongodbatlas-operator
          # Replace this with the built image name
          image: knappek/mongodbatlas-operator:0.0.7
          command:
          - mongodbatlas-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mongodbatlas-operator"
            - name: ATLAS_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: privateKey
                  name: example-monogdb-atlas-project
            - name: ATLAS_PUBLIC_KEY
              value: toppaljd
            - name: RECONCILIATION_TIME
              value: "120"
